const defaultTextbooks = [
  { id: 1,
    title: 'Math 101',
    price: 10,
    subject: 'Mathematics',
    course: 'Algebra',
    condition: 'Good',
    isbn: '12345',
    description: '',
    picture: 'https://via.placeholder.com/150' },
  { id: 2,
    title: 'History of Art',
    price: 50,
    subject: 'Arts',
    course: 'History',
    condition: 'Fair',
    isbn: '23456',
    description: '',
    picture: 'https://via.placeholder.com/150' },
  { id: 3,
    title: 'Science Basics',
    price: 150,
    subject: 'Science',
    course: 'Physics',
    condition: 'Excellent',
    isbn: '34567',
    description: '',
    picture: 'https://via.placeholder.com/150' },
  { id: 4,
    title: 'Advanced Physics',
    price: 300,
    subject: 'Science',
    course: 'Physics',
    condition: 'Good',
    isbn: '45678',
    description: '',
    picture: 'https://via.placeholder.com/150' },
  { id: 5,
    title: 'Modern Literature',
    price: 500,
    subject: 'Arts',
    course: 'Literature',
    condition: 'Excellent',
    isbn: '56789',
    description: '',
    picture: 'https://via.placeholder.com/150' },
  { id: 6,
    title: 'Data Structures',
    price: 700,
    subject: 'Computer Science',
    course: 'Algorithms',
    condition: 'Fair',
    isbn: '67890',
    description: '',
    picture: 'https://via.placeholder.com/150' },
];

export default defaultTextbooks;
